[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32 --baud 1000000"
#  --log-format defmt

[env]
ESP_LOG="info"
#DEFMT_LOG="info,altreg_fire27_rs::io=debug"
DEFMT_LOG="info,altreg_fire27_rs::state=debug,altreg_fire27_rs::control=debug"
DEP_LV_CONFIG_PATH={ value = "./lvgl_rust_sys/lvgl", relative = true }
ESP_HAL_CONFIG_PLACE_SPI_MASTER_DRIVER_IN_RAM="true"


[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-C", "link-args=-Wl,-Map=target/app.map"
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
