
esp32:
  board: m5stack-core-esp32

substitutions:
  vbat_io: GPIO35
  rpm_io: GPIO5

i2c:
  id: bus_a
  frequency: 400kHz
  scan: False
  sda: GPIO21
  scl: GPIO22

one_wire:
  - platform: gpio
    pin: GPIO17

binary_sensor:
  - platform: gpio
    name: "Button A"
    pin:
      number: 39
      inverted: true
    filters:
    - autorepeat:
      - delay: 1s
        time_off: 400ms
        time_on: 100ms
    on_press:
      then:
      - number.decrement:
          id: set_current
          cycle: false

  - platform: gpio
    name: "Button B"
    pin:
      number: 38
      inverted: true
    on_press:
      then:
        - number.set:
            id: set_voltage
            value: 12.0
        - number.set:
            id: set_current
            value: 0.001
        - switch.toggle: oe_switch

  - platform: gpio
    name: "Button C"
    pin:
      number: 37
      inverted: true
    filters:
    - autorepeat:
      - delay: 1s
        time_off: 400ms
        time_on: 100ms
    on_press:
      then:
      - number.increment:
          id: set_current
          cycle: false

# GPIO pin of the display backlight
output:
  - platform: ledc
    pin: 32
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON

spi:
  clk_pin: 18
  mosi_pin: 23
#  miso_pin: 19
  interface: spi3

display:
  - platform: ili9xxx
    model: M5Stack
    id: m5stack_display
    invert_colors: true
    color_palette: 8BIT
    pixel_mode: 16bit
    cs_pin: 14
    dc_pin: 27
    reset_pin: 33
    rotation: 0
    show_test_card: false
    data_rate: 40MHz
    update_interval: 0.1s
    auto_clear_enabled: false
    lambda: !include { file: lambda_gui.yaml }


sensor:
  - platform: template
    name: "Battery voltage"
    id: v_bat
  - platform: template
    name: "Battery current"
    id: i_bat
    web_server:
      sorting_group_id: bat_data
  - platform: template
    name: "Battery SoC"
    id: soc
    web_server:
      sorting_group_id: bat_data
