esphome:
  platformio_options:
    upload_speed: 2000000
    board_build.f_cpu: 240000000L
    board_build.f_flash: 80000000L
    board_build.arduino.memory_type: qio_qspi
#    platform: https://github.com/pioarduino/platform-espressif32.git#f4def7ffb924cd9657f8f32ee52902ad550f752e  # develop from 03.05.25
    platform: https://github.com/pioarduino/platform-espressif32.git#54.03.20
    # build_flags:
    #   -mfix-esp32-psram-cache-issue

esp32:
  flash_size: 4MB
  # framework:
  #   type: arduino
  framework:
    type: esp-idf
    version: 5.4.0  # must match platform option!
    sdkconfig_options:
      # ESP32
      CONFIG_ESP32_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "240"
      CONFIG_ESP_MAIN_TASK_STACK_SIZE: "12000"
#      CONFIG_STDATOMIC_S32C1I_SPIRAM_WORKAROUND: "n"

      # CONFIG_SPIRAM_USE_MEMMAP: "y"
      # CONFIG_SPIRAM_USE_CAPS_ALLOC: "y"
      # CONFIG_SPIRAM_USE_MALLOC: "y"
debug:
  update_interval: 5s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    psram:
      name: "Free PSRAM"


switch:
  - platform: restart
    name: "Restart Switch"
