external_components:
  - source: github://hsteinhaus/esphome-gppid@master
    refresh: 0s

esphome:
  on_boot:
    then:
      - number.set:
          id: kp_num
          value: !lambda return id(idle_pid).get_kp();
      - number.set:
          id: ki_num
          value: !lambda return id(idle_pid).get_ki();
      - number.set:
          id: kd_num
          value: !lambda return id(idle_pid).get_kd();

number:
  - platform: template
    id: kp_num
    name: "kP"
    step: 0.001
    min_value: 0.0
    max_value: 0.05
    optimistic: True
    web_server:
      sorting_group_id: voltage_pid_group
  - platform: template
    id: ki_num
    name: "kI"
    step: 0.001
    min_value: 0
    max_value: 0.5
    optimistic: True
    web_server:
      sorting_group_id: voltage_pid_group
  - platform: template
    id: kd_num
    name: "kD"
    step: 0.0001
    min_value: 0
    max_value: 0.003
    optimistic: True
    web_server:
      sorting_group_id: voltage_pid_group

  - platform: template
    id: v_target_num
    name: "Target voltage"
    unit_of_measurement: V
    step: 0.1
    initial_value: 20.
    min_value: 0
    max_value: 30
    optimistic: True
    web_server:
      sorting_group_id: voltage_pid_group

  - platform: template
    id: i_target_num
    name: "Target voltage"
    unit_of_measurement: V
    step: 0.1
    initial_value: 10
    min_value: 0
    max_value: 30
    optimistic: True
    web_server:
      sorting_group_id: voltage_pid_group

pid:
  - id: idle_pid
    current_value: v_alt
    target_number: v_target_num
    # target_sensor: v_target_sensor
    # output:
    #   id: i_field_out
    #   min: 0.01
    #   max: 0.5
    control_parameters:
      kp: 0.011
      ki: 0.2
      kd: 0.001
      min_integral: -0.5
      max_integral: 0.5
      # kp_num: kp_num
      # ki_num: ki_num
      # kd_num: kd_num
      #output_averaging_samples: 5      # smooth the output over 5 samples
      derivative_averaging_samples: 5  # smooth the derivative value over 10 samples
    # deadband_parameters:
    #   threshold_high: 0.01
    #   threshold_low: -0.01

  - id: current_pid
    current_value: i_bat
    target_number: i_target_num
    # target_sensor: v_target_sensor
    # output:
    #   id: i_field_out
    #   min: 0.01
    #   max: 0.5
    control_parameters:
      kp: 0.05
      ki: 0.0
      kd: 0.0
      min_integral: -0.5
      max_integral: 0.5
      kp_num: kp_num
      ki_num: ki_num
      kd_num: kd_num
      #output_averaging_samples: 5      # smooth the output over 5 samples
      derivative_averaging_samples: 5  # smooth the derivative value over 10 samples
    # deadband_parameters:
    #   threshold_high: 0.01
    #   threshold_low: -0.01

sensor:
  - platform: pid
    id: idle_pid_out
    name: "Idle PID output"
    pid_id: idle_pid
    unit_of_measurement: A
    accuracy_decimals: 3
    type: RESULT
    web_server:
      sorting_group_id: voltage_pid_group
  - platform: pid
    id: current_pid_out
    name: "Current PID output"
    pid_id: current_pid
    unit_of_measurement: A
    accuracy_decimals: 3
    type: RESULT
    web_server:
      sorting_group_id: voltage_pid_group

  - platform: combination
    type: linear
    name: "Field current"
    sources:
      - source: idle_pid_out
        coeffecient: 0.0
      - source: current_pid_out
        coeffecient: 1.0
    on_value:
      then:
        - number.set:
            id: pps_set_current
            value: !lambda 'return x < 0.5 ? x : 0.5;'



# output:
#   - platform: template
#     id: i_field_out
#     type: float
#     write_action:
#       - number.set:
#           id: pps_set_current
#           value: !lambda return state;
